# fly.toml app configuration file generated for htmx-chat on 2024-08-27T20:50:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'htmx-chat'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 1323
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
